project:
  type: website

website:
  title: "Calendario Acad√©mico UAI"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: assets/calendar.css
