project:
  type: website

website:
  title: "Calendario Acad√©mico UAI"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Acerca de"
        href: acerca-de.qmd
    tools:
      - icon: github
        href: https://github.com/rocarvaj/calendario-uai

format:
  html:
    theme: cosmo
    toc: false
